# This file is optional, but lets you use Paper's extra features

# Required: plugin metadata
name: Art3misPaperPlugin
version: 1.0
main: project.art3mis.plugin.Main

# Optional Paper-only enhancements
# You do NOT need to repeat everything from plugin.yml, only what you want to override or enhance.
# Example: Add Paper loader version, bootstrapper, or platform-specific features

# Minimum Paper version required for your plugin
loader:
  api-version: 1.0

# Optionally, add bootstrapper if you use it
#bootstrapper: your.package.BootstrapClass

# Optionally, you can specify which platforms (e.g., Paper, Folia) your plugin is compatible with
platforms:
  - paper

# Additional Paper-specific config can go here