# paper-plugin.yml

name: ProjectArt3misPlugin
version: '1.0-SNAPSHOT'
main: project.Art3mis.Plugin.Main
api-version: '1.21'
authors: [ MoNoLidThZ ]
description: Art3mis Devlopment
website: https://art3mis.project

# Paper-specific fields (optional, but recommended)
loader:
  type: JAVA

# Command definitions (Paper supports the same format as plugin.yml)
commands:
  map:
    description: Gives the player a map with specific ID
    usage: /map <map_id>
    permission: Art3misCmds.map

permissions:
  Art3misCmds.map:
    description: Allows using the /map command
    default: false