name: ProjectArt3misPlugin
version: '1.0-SNAPSHOT'
main: project.Art3mis.Plugin.Main
api-version: '1.21'
authors: [ MoNoLidThZ ]
description: Art3mis Devlopment
website: https://art3mis.project

commands:
  map:
    description: Gives the player a map with specific ID
    usage: /map <map_id>
    permission: Art3misCmds.map
  givepet:
    description: "Transfer ownership of your pets to other people"
    usage: 'Usage: /givepet [player|cancel]'
    permission: "givepet.use"
    permission-message: "No permission!"
permissions:
  Art3misCmds.map:
    description: Allows using the /map command
    default: false
  Art3misCmds.givepet:
    description: "Allows players to use the /givepet command"
    default: true