name: Art3misMapPlugin
version: 1.0
main: project.art3mis.plugin.Main
api-version: 1.20
commands:
  map:
    description: Gives the player a map with specific ID
    usage: /map <map_id>
    permission: Art3misCmds.map
permissions:
  Art3misCmds.map:
    description: Allows using the /map command
    default: true
